// Flat C exports observed in DMCmnUtils.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef DMCMNUTILS_C_H
#define DMCMNUTILS_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: DecodeBase64W (ABI unverified)
// Export: EncodeBase64 (ABI unverified)
// Export: EncodeBase64W (ABI unverified)
// Export: DmExecuteProcessAndCollect (ABI unverified)
// Export: DmGetUserOidFromTokenBroker (ABI unverified)
// Export: DmInitializeContainer (ABI unverified)
// Export: DmQueryGraphAgentUser (ABI unverified)
// Export: DmReleaseContainer (ABI unverified)
// Export: DmStartContainerActivity (ABI unverified)
// Export: DmStopContainerActivity (ABI unverified)
// Export: DmMdmSign (ABI unverified)
// Export: DmCopyDirectoryRecursive (ABI unverified)
// Export: DmCreateFileSafe (ABI unverified)
// Export: DmGetFileSize (ABI unverified)
// Export: ComputeHmac (ABI unverified)
// Export: CreateRebootCSPTasksFromRegistry (ABI unverified)
// Export: DeleteRebootCSPTaskInRegistry (ABI unverified)
// Export: WriteRebootCSPTaskToRegistry (ABI unverified)
// Export: DMGetClientHardwareUID (ABI unverified)
// Export: DMGetDeviceClientID (ABI unverified)
// Export: DMSetDeviceClientID (ABI unverified)
// Export: GetPhoneUID (ABI unverified)
// Export: DmGetEnrollmentTypeName (ABI unverified)
// Export: DmGetEnrollmentTypeValue (ABI unverified)
// Export: GetHeader (ABI unverified)
// Export: IsDesktopSku (ABI unverified)
// Export: IsServerVersionOrAbove (ABI unverified)
// Export: IsWvdFeatureAllowed (ABI unverified)
// Export: IsWvdSku (ABI unverified)
// Export: OmDmRegistryAllocAndGetString (ABI unverified)
// Export: OmaDmRegistryDeleteValue (ABI unverified)
// Export: OmaDmRegistryGetAllSubKeys (ABI unverified)
// Export: OmaDmRegistryGetAllValues (ABI unverified)
// Export: OmaDmRegistryGetBinary (ABI unverified)
// Export: OmaDmRegistryGetDWORD (ABI unverified)
// Export: OmaDmRegistryGetString (ABI unverified)
// Export: OmaDmRegistryRetrieveCurrentUsersHKCU (ABI unverified)
// Export: OmaDmRegistrySetBinary (ABI unverified)
// Export: OmaDmRegistrySetDWORD (ABI unverified)
// Export: OmaDmRegistrySetString (ABI unverified)
// Export: SetConnectionPriority (ABI unverified)
// Export: Hash_Create (ABI unverified)
// Export: Hash_Delete (ABI unverified)
// Export: Hash_Destroy (ABI unverified)
// Export: Hash_DestroyCallback (ABI unverified)
// Export: Hash_EnumCallback (ABI unverified)
// Export: Hash_Get (ABI unverified)
// Export: Hash_Insert (ABI unverified)
// Export: Hash_SetBucketThreshold (ABI unverified)
// Export: DmGetSmbiosSerialNumber (ABI unverified)
// Export: DmGetTpmInfo (ABI unverified)
// Export: DmGetTpmIsAlgorithmSupported (ABI unverified)
// Export: DmGetTpmState (ABI unverified)
// Export: DmGetIMEI (ABI unverified)
// Export: DmIsDeviceConnected (ABI unverified)
// Export: DmIsDeviceRoaming (ABI unverified)
// Export: DmRegisterRoamingNotification (ABI unverified)
// Export: DmUnregisterRoamingNotification (ABI unverified)
// Export: GetPGListRegKeyName (ABI unverified)
// Export: GetICCID (ABI unverified)
// Export: GetIMEI (ABI unverified)
// Export: GetIMSI (ABI unverified)
// Export: GetIMSIByIccID (ABI unverified)
// Export: GetPhoneNumber (ABI unverified)
// Export: QueryPolicy (ABI unverified)
// Export: SetPolicy (ABI unverified)
// Export: DmCreateTask (ABI unverified)
// Export: DmDeleteTask (ABI unverified)
// Export: DmDeleteTaskFolder (ABI unverified)
// Export: DmDisableTask (ABI unverified)
// Export: DmEnableTask (ABI unverified)
// Export: DmIsTaskScheduled (ABI unverified)
// Export: DmIsTaskScheduledAndEnabled (ABI unverified)
// Export: DmRunTask (ABI unverified)
// Export: DmEnumUsers (ABI unverified)
// Export: DmGetActiveUserSid (ABI unverified)
// Export: DmGetAllActiveUserSids (ABI unverified)
// Export: DmGetCurrentUserSid (ABI unverified)
// Export: DmGetCurrentUserToken (ABI unverified)
// Export: DmGetUserSidFromToken (ABI unverified)
// Export: DmGetUserTokenFromSid (ABI unverified)
// Export: DmImpersonate (ABI unverified)
// Export: DmIsRunningInSystemContext (ABI unverified)
// Export: DmIsSystemOrAdmin (ABI unverified)
// Export: DmIsSystemOrUserIsAdmin (ABI unverified)
// Export: DmRevertToSelf (ABI unverified)
// Export: BigStrcat (ABI unverified)
// Export: CopyString (ABI unverified)
// Export: CreateBstrArray (ABI unverified)
// Export: DmStringCchPrintfAllStrings (ABI unverified)
// Export: EscapeStringW (ABI unverified)
// Export: InvStrCmpIW (ABI unverified)
// Export: InvStrCmpNIW (ABI unverified)
// Export: InvStrCmpNW (ABI unverified)
// Export: InvStrCmpW (ABI unverified)
// Export: MBToUnicode (ABI unverified)
// Export: SafeMultiByteToWideChar (ABI unverified)
// Export: SafeStringToDword (ABI unverified)
// Export: SafeWideCharToMultiByte (ABI unverified)
// Export: UnicodeToMB (ABI unverified)
// Export: BinaryToHexString (ABI unverified)
// Export: HexStringToBinary (ABI unverified)
// Export: DmRaiseToastNotification (ABI unverified)
// Export: DmRaiseToastNotificationAndWait (ABI unverified)
// Export: DmRemoveToastNotification (ABI unverified)
// Export: DmRemoveToastNotificationByExecutablePath (ABI unverified)
// Export: DmPlayNotificationSound (ABI unverified)
// Export: DmCheckIfAadAccountLoggedOn (ABI unverified)
// Export: DmCleanupAgentGovernanceAgentIds (ABI unverified)
// Export: DmProcessAgentGovernancePolicy (ABI unverified)
// Export: DmGetAadDeviceMdmEnrollmentResourceUrlForRecovery (ABI unverified)
// Export: DmGetAadDeviceMdmEnrollmentResourceUrlWithDiscovery (ABI unverified)
// Export: DmGetAadDeviceToken (ABI unverified)
// Export: DmGetAadDeviceTokenWithDiscovery (ABI unverified)
// Export: DmGetAadEnrollmentResource (ABI unverified)
// Export: DmGetAadUserToken (ABI unverified)
// Export: DmInvalidateAadDeviceToken (ABI unverified)
// Export: DmInvalidateAadUserToken (ABI unverified)
// Export: DmRequestAadUserToken (ABI unverified)
// Export: DmCancelGetUserPermissionAsync (ABI unverified)
// Export: DmGetUserEditFieldInput (ABI unverified)
// Export: DmGetUserPermission (ABI unverified)
// Export: DmGetUserPermissionAsync (ABI unverified)
// Export: DmInformUser (ABI unverified)
// Export: DmWnfGetNotification (ABI unverified)
// Export: DmWnfPublish (ABI unverified)
// Export: DmWnfQuery (ABI unverified)
// Export: DmCheckAik (ABI unverified)
// Export: DmDiagnoseEkAikMissing (ABI unverified)
// Export: DmGenerateAttestationClaims (ABI unverified)
// Export: DmGenerateMaaAttestationClaims (ABI unverified)
// Export: DmGenerateMaaAttestationClaimsOld (ABI unverified)
// Export: DmGetAikKeyForAlgorithm (ABI unverified)
// Export: DmGetKeyFromContext (ABI unverified)
// Export: DmGetKeyNameFromContext (ABI unverified)
// Export: DmGetTargetAik (ABI unverified)
// Export: DmGetTargetAikWithRetry (ABI unverified)
// Export: DmSetWindowsAIKStorageLocationOld (ABI unverified)
// Export: DmGetCorrelationVectorForDmSession (ABI unverified)
// Export: DmInitializeCVForLocalConfigSession (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // DMCMNUTILS_C_H
